# Generated by Django 5.2.8 on 2025-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poetry", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="poem",
            options={
                "verbose_name": "Произведение",
                "verbose_name_plural": "Произведения",
            },
        ),
        migrations.AlterField(
            model_name="poem",
            name="likes",
            field=models.IntegerField(default=0, verbose_name="Лайки"),
        ),
    ]
